#Sat Aug 15 13:32:47 IST 2026
org.gradle.caching=true
VERSION_NAME_OPEN=4.0.9
kotlin.incremental=true
VERSION_NAME_CLOSED=3.0.22
VERSION_NAME_INTERNAL=2.6.183
org.gradle.parallel=true
VERSION_CODE=255
org.gradle.jvmargs=-Xmx4096m -XX\:+UseG1GC --add-opens\=jdk.compiler/com.sun.tools.javac.main\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.util\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.tree\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.processing\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.model\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.code\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.api\=ALL-UNNAMED --add-opens\=jdk.compiler/com.sun.tools.javac.comp\=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
RELEASE_TRACK=closed
android.suppressUnsupportedCompileSdk=36
android.compileSdkVersion=36
VERSION_NAME=3.0.22
kotlin.compiler.execution.strategy=in-process
org.gradle.workers.max=4
android.targetSdkVersion=36
kotlin.gradle.plugin.statistics=false
kotlin.incremental.useClasspathSnapshot=true
